### ISSUE TITLE
* .env.js File is Missing *

### ISSUE THREAD

**Issue by syedrahman24** [sramezani/resume-builder-server#3]
File named .env.js is missing in the project source files. 

Error: Module Not Found.

![issue1](https://user-images.githubusercontent.com/57063763/104581279-595ef800-5684-11eb-82ed-403c077faf1e.png)

**Comment by sramezani** [comment]
create `.env.js` file on your project route:

```
const env = {
    connectionString: 'your-mongo-db',
};

module.exports = env;
```
